#!/bin/bash

plotter_name=$1
window_length=$2
window_lag=$3
speedup=$4

rate=$(( speedup / window_lag ))

echo 'rate:' $rate

ffmpeg -y -r $rate -i %5d.png -s hd1080 -vcodec libx264 -vpre libx264-lossless_slower  -r $rate $plotter_name-$window_length.mp4
