"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['metatoneLiveLoggingProcessor.py']
DATA_FILES = ['2013-07-01-TrainingData-classifier.p']
# INCLUDES = ['sklearn','sklearn.utils','sklearn.ensemble','sklearn.utils.lgamma'],
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/charles/Dropbox/Metatone/touch-point-performance-analysis/MetatoneClassifier/metatone.icns',
 'includes':'sklearn.utils.lgamma',
 'plist': {'CFBundleName': 'MetatoneClassifier',
 	'CFBundleShortVersionString':'0.1.0', # must be in X.X.X format
 	'CFBundleVersion': '0.1.0',
 	'CFBundleIdentifier':'au.com.charlesmartin.MetatoneClassifier', #optional
 	'NSHumanReadableCopyright': '© 2014 Charles Martin', #optional
 	'CFBundleDevelopmentRegion': 'English', #optional - English is default
 	}
 }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
